/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Ticket;
import org.example.entities.User;
import org.example.services.TrainServices;
import org.example.services.UserServices;
import org.example.utils.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.UUID;

public class App {

    public static void main(String[] args) {
        System.out.println("Welcome to Train Ticketing Backend");
        System.out.println("1. SignUp\n2. Login\n3. Search Available Trains\n4. Book Tickets\n5. EMail Confirmation");
        System.out.print("Enter Option: ");
        Scanner scanner = new Scanner(System.in);
        int opt = scanner.nextInt();
        User user;
        switch (opt) {
            case 1:
                System.out.println("Enter Name: ");
                String nameToSignUp = scanner.next();
                scanner.nextLine();
                System.out.println("Enter Password: ");
                String passwordToSignUp = scanner.next();
                user = new User(
                        nameToSignUp,
                        passwordToSignUp,
                        UserServiceUtil.hashPassword(passwordToSignUp),
                        new ArrayList<>(),
                        UUID.randomUUID().toString()
                );
                try {
                    UserServices userServices = new UserServices();
                    if (userServices.signUser(user)) {
                        System.out.println("Thank you for signing up " + nameToSignUp + " 😇!!");
                    }
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }

            case 2:
                System.out.println("Enter Name: ");
                String nameToLogin = scanner.next();
                scanner.nextLine();
                System.out.println("Enter Password: ");
                String passwordToLogin = scanner.next();
                user = new User(
                        nameToLogin,
                        passwordToLogin,
                        UserServiceUtil.hashPassword(passwordToLogin),
                        new ArrayList<>(),
                        UUID.randomUUID().toString()
                );
                try {
                    UserServices userServices = new UserServices(user);
                    if (userServices.loginUser()) {
                        System.out.println("Welcome Back " + nameToLogin + " 🙂");
                    }
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }

            case 3:
                System.out.print("Enter Source: ");
                String source = scanner.next();
                System.out.print("Enter Destination: ");
                String destination = scanner.next();
                try {
                    TrainServices trainServices = new TrainServices();
                    trainServices.findTrains(source, destination);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            case 4:
                try {
                    TrainServices trainServices = new TrainServices();
                    Ticket ticketBooked = trainServices.bookTickets();
                    UserServices userServices = new UserServices();
                    userServices.saveBookedTicket(ticketBooked);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            case 5:
                System.out.print("Enter your Email: ");
                String email = scanner.next();
                try {
                    UserServices userServices = new UserServices();
                    userServices.emailConfirmation(email);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
        }
    }
}
